### ISSUE TITLE
Html+CSS专题篇

### ISSUE THREAD

**Issue by linzhenjie** [linzhenjie/blog#12]
### meta viewport相关

````html
<meta http-equiv=”X-UA-Compatible” content=”IE=edge,chrome=1″/> <!-- 优先使用 IE 最新版本和 Chrome Frame -->
<meta name=”robots” content=”index,follow”/>   <!-- 搜索引擎抓取 -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" /><!-- 为移动设备添加 viewport -->
<meta name=”apple-mobile-web-app-title” content=”标题”> <!-- IOS主屏后的标题 -->
<meta name=”apple-mobile-web-app-capable” content=”yes”/> <!-- 删除默认的苹果工具栏和菜单栏。 -->
<meta name=”apple-mobile-web-app-status-bar-style” content=”black”/> <!-- 控制状态栏显示样式 -->
<meta name=”format-detection” content=”telphone=no, email=no”/>  <!--键盘输入格式检测 -->
<meta name=”renderer” content=”webkit”>  <!-- 多核浏览器优先启用webkit -->
<meta name=”screen-orientation” content=”portrait”>   <!-- uc强制竖屏 -->
<meta name=”full-screen” content=”yes”>   <!-- UC强制全屏 -->
<meta name=”browsermode” content=”application”> <!--  UC应用模式 -->
<meta name=”x5-orientation” content=”portrait”> <!--QQ强制竖屏 -->
<meta name=”x5-fullscreen” content=”true”>  <!-- QQ强制全屏 -->
<meta name=”x5-page-mode” content=”app”>   <!-- QQ应用模式 -->
<!-- 设置页面不缓存 -->
<meta http-equiv=”pragma” content=”no-cache”>
<meta http-equiv=”cache-control” content=”no-cache”>
<meta http-equiv=”expires” content=”0″>
`````

### 垂直水平居中方式
````html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <style>
      html,body { width: 100%; height: 100%; margin: 0; padding: 0;}
      .content { width: 300px; height: 300px; background: orange;}
    </style>
    <!--这里为实现代码-->
</head>
<body>
    <div class="content"></div>
</body>
</html>
````
**flex方式：**
````css
body {
  display: flex;
  align-items: center;
  justify-content: center;
}
````
**absolute 方式：**
````css
.content {
  position: absolute;
  left:50%;
  top: 50%;
  transform: translateX(-50%) translateY(-50%);
}
````
**vertical-align 方式：**
````css
body {
  position: fixed;
  text-align: center;
}
body:after {
  content: '';
  display: inline-block;
  height: 100%;
  vertical-align: middle;
}
.content {
  display: inline-block;
  vertical-align: middle;
}
````
**calc 方式：**
````css
body{
  height: 100vh;
  overflow: hidden;
}
.content{
  margin: calc(50vh - 150px) auto 0 auto; 
}
````
**table 方式：**
````css
html{
  display: table;
}
body{
  display: table-cell;
  vertical-align: middle;
}
.content{
  margin: auto;
}
````
### css三角形和箭头的实现
````css
.triangle {
  /*占位符*/
  position: relative;
  width: 50px;
  height: 50px;
}
.triangle:after{
  content: "";
  position: absolute;
  border: 25px solid transparent;
  border-bottom-color: blue;
  transform: rotate(180deg);
}
.arrow {
  /*占位符*/
  position: relative;
  width: 50px;
  height: 50px;
}
.arrow:after {
  content: "";
  position: absolute;
  top:50%;
  width: 25px;
  height: 25px;
  border-top: 2px solid blue;
  border-right: 2px solid blue;
  transform: rotate(45deg)  translateY(-50%);
}
````
